#!bin/sh
case "$(echo -e "Shutdown\nRestart\nLogout\nSuspend\nLock" | dmenu \
    -i -p  \
    "Power menu:" -l 5)" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Logout) killall dwm;;
        Suspend) exec systemctl suspend;;
        Lock) exec slock;;
esac
