#!/usr/bin/env bash

# Check if battery is present
if [ -e "/sys/class/power_supply/BAT0" ]; then
    batstat="$(cat /sys/class/power_supply/BAT0/status)"
    battery="$(cat /sys/class/power_supply/BAT0/capacity)"
    if [[ $batstat != 'Discharging' ]]; then
        if [[ $battery -ge 99 ]]; then
            batstat=" "
        elif [[ $battery -ge 75 ]]; then
            batstat=" "
        elif [[ $battery -ge 50 ]]; then
            batstat=" "
        elif [[ $battery -ge 25 ]]; then
            batstat=" "
        elif [[ $battery -ge 1 ]]; then
            batstat=" "
        fi
    else
        if [[ $battery -le 5 ]]; then
            batstat=""
        elif [[ $battery -le 25 ]]; then
            batstat=""
        elif [[ $battery -le 50 ]]; then
            batstat=""
        elif [[ $battery -le 75 ]]; then
            batstat=""
        elif [[ $battery -le 97 ]]; then
            batstat=""
        elif [[ $battery -le 100 ]]; then
            batstat=""
        fi
    fi
    echo "$batstat $battery%"
else
    echo ""
fi
