#!/bin/sh

case $BLOCK_BUTTON in
    1)
        st -e nmtui
        pkill -RTMIN+4 dwmblocks
        ;;
esac

# Wifi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
    printf " %s%%" "$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
    [ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && printf "" || printf " "
fi

# Ethernet
[ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ] && printf " " || printf ""

# TUN
[ -n "$(cat /sys/class/net/tun*/operstate 2>/dev/null)" ] && printf " " || printf ""

echo
